# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TaMSwMpyhIZm0+J/RJBf7+hw46YQ9bVFFlwGVm/0MMSOBm0DsAKZhXcKyu6nUE82ey5n3mriimu7EV1LTZIgeEFUNqtBwEi1PTAWYo8ZeEtA94f0HjnPC+Ge3tsPTf/B9vAP43QTo1tKpq53bPErdEAkdPXnpFV+VhUuxS48ZrFdATXaeaG5mGVykz/ZVJn/X4nRMFSfmd6pXJzx/7GjwaLZaYxrjuLGA5s9TWnpWlYJLHJ/6v80vew6RJJDZCxWddcxzBUTiCVhdIXupTnuA0NQENwhxVM6yE4Nve/B+wtj4tP2QtQg7hqovSgXh5mnRHfFqhTlWCIr4CtsRq1BtZiulGAF2j0NKu2lNwEBxw+m6taMP4CIZiR+jRwkdEzgoXrkPgpBYpK0RHu+DWOKUi2SuAGbrxUu7d14gMCNzrnaa6XMJ4BM4vxRzX7vZYrvid8+9TJoAM0VB9w9wW+Ty6K53HGkPd3Dvr6jFwjbH3CgAQt7FtPSvvMeYFipJir3tks6q3BAXrayzg4W2ToVuPQm75sj6qRrRT89mADg+pucjMuqNLIA5uN4KhoiO1iQa0jUGeiuJbN5udDzgngCftxG8fHWpp5WGGVidLAihh+f9Kb2KMeR3G7/lLKzul5tIXwY0to8XbunWFIzDtjCivlDrS3N5uKgjn0yP1oG1bY="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi