appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: TaMSwMpyhIZm0+J/RJBf7+hw46YQ9bVFFlwGVm/0MMSOBm0DsAKZhXcKyu6nUE82ey5n3mriimu7EV1LTZIgeEFUNqtBwEi1PTAWYo8ZeEtA94f0HjnPC+Ge3tsPTf/B9vAP43QTo1tKpq53bPErdEAkdPXnpFV+VhUuxS48ZrFdATXaeaG5mGVykz/ZVJn/X4nRMFSfmd6pXJzx/7GjwaLZaYxrjuLGA5s9TWnpWlYJLHJ/6v80vew6RJJDZCxWddcxzBUTiCVhdIXupTnuA0NQENwhxVM6yE4Nve/B+wtj4tP2QtQg7hqovSgXh5mnRHfFqhTlWCIr4CtsRq1BtZiulGAF2j0NKu2lNwEBxw+m6taMP4CIZiR+jRwkdEzgoXrkPgpBYpK0RHu+DWOKUi2SuAGbrxUu7d14gMCNzrnaa6XMJ4BM4vxRzX7vZYrvid8+9TJoAM0VB9w9wW+Ty6K53HGkPd3Dvr6jFwjbH3CgAQt7FtPSvvMeYFipJir3tks6q3BAXrayzg4W2ToVuPQm75sj6qRrRT89mADg+pucjMuqNLIA5uN4KhoiO1iQa0jUGeiuJbN5udDzgngCftxG8fHWpp5WGGVidLAihh+f9Kb2KMeR3G7/lLKzul5tIXwY0to8XbunWFIzDtjCivlDrS3N5uKgjn0yP1oG1bY=}
bot:
  automerge: true
